### PR TITLE
feature 497 headers

### LINKED ISSUE #313: Documentation: Make Headers Consistent in METcalcpy User's Guides
This is a sub-issue of [METplus: Documentation: Make Headers Consistent in METplus components User's Guides #898](https://github.com/dtcenter/METplus/issues/898).

## Describe the Sub-Issue ##
This task is for all METplus component.  This specific issue is for METcalcpy only:

The headers for the METplus components User's Guides may not be consistent, but we want them to be. 

Here is the syntax from the RST docs (https://www.sphinx-doc.org/en/master/usage/restructuredtext/basics.html#sections):

\# with overline, for parts (e.g. the RTD documentation for the component (i.e. docs/index.rst), each guide (e.g. User's Guide, Contributor's Guide) (i.e. docs/Users_Guide/index.rst, docs/Contributors_Guide/index.rst))
\* with overline, for chapters
=, for sections
-, for subsections
^, for subsubsections
", for paragraphs

### Time Estimate ###
1 to 3 days of work

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED CYCLE ASSIGNMENT** label
- [x] Select **Milestone** as the next official version or **Future Versions**

### PR DESCRIPTION
**Pull request by lisagoodrich**
## Pull Request Testing ##

- [x] Describe testing already performed for these changes:</br>. This issue had to be re-opened due to confusion about the best way to label index.rst files.  They are treated differently depending on where they are located.  Below are notes from @jprestop.

https://github.com/dtcenter/METviewer/pull/502#event-10836296932 
[@lisagoodrich](https://github.com/lisagoodrich) Thanks for all of your work on this task. I added a few suggestions that you can just accept the changes for, however, for the top level docs/index.rst, could you please change those headers back to what they were? Let me know if you want to talk about this again, but we had discussed how the top level index wasn't really a "part" whereas the User's Guide's and Contributor's Guide's index.rst files were "parts". So, we decided just to leave the top level index.rst files alone. You can verify this by looking at the already merged METplotpy file (https://raw.githubusercontent.com/dtcenter/METplotpy/develop/docs/index.rst) and the already merged METplus file (https://raw.githubusercontent.com/dtcenter/METplus/develop/docs/index.rst). METcalcpy was also completed but it looks like it is not the same as the others and needs to be fixed as well (https://raw.githubusercontent.com/dtcenter/METcalcpy/develop/docs/index.rst) - apologies for missing that in PR review of METcalcpy.

- [x] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br> Confirm the header change is correct, using = instead of #.
Please squash and merge and close the branch.  I don't have permission to do this.

- [x] Do these changes include sufficient documentation updates, ensuring that no errors or warnings exist in the build of the documentation? **[No errors]**

- [ x Do these changes include sufficient testing updates? **[Yes]**

- [x] Will this PR result in changes to the test suite? **[No]**</br>
If **yes**, describe the new output and/or changes to the existing output:</br>

- [x] Please complete this pull request review by **[11/13/23]**.</br>

## Pull Request Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [x] Add any new Python packages to the [METplus Components Python Requirements](https://metplus.readthedocs.io/en/develop/Users_Guide/overview.html#metplus-components-python-requirements) table.
- [x] Review the source issue metadata (required labels, projects, and milestone).
- [x] Complete the PR definition above.
- [x] Ensure the PR title matches the feature or bugfix branch name.
- [x] Define the PR metadata, as permissions allow.
Select: **Reviewer(s)**
Select: **Organization** level software support **Project** or **Repository** level development cycle **Project**
Select: **Milestone** as the version that will include these changes
- [x] After submitting the PR, select the :gear: icon in the **Development** section of the right hand sidebar. Search for the issue that this PR will close and select it, if it is not already selected.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue and delete your feature or bugfix branch from GitHub.

### CODE REVIEW

**Comment by jprestop** [comment]
@lisagoodrich I changed the Project from METplus-Wrappers-6.0.0 Development to METplus-Analysis-6.0.0 Development since this PR is for METcalcpy and not for METplus wrappers.  I also changed the Milestone from METcalcpy-2.1.1 Bugfix to METcalcpy-3.0.0 since this isn't a bugfix but rather a change for the upcoming release.

**Review by jprestop — APPROVED** [review]
Thanks @lisagoodrich for your work on this task. I have verified that all tests pass.  I approve this request.

**Comment by lisagoodrich** [comment]
@jprestop who do I ask to Merge this pull request?  I'm unable to merge it.  Thank you for making corrections to the projects and developments.

**Comment by jprestop** [comment]
HI @lisagoodrich.  I'm sorry, I always forget that you do not have squash and merge permissions here.  :( I will take care of it.

**Pull request merged**
