### PR TITLE
Feature_342_add_write_mpr_file

### LINKED ISSUE #342: Move the MPR file write script from the Blocking/WR area to the util area
*Replace italics below with details for this issue.*

## Describe the Task ##
Separate the write_mpr_file code from the Blocking_WeatherRegime_util.py to the util area so it can be used from other use cases.  This will include making some changes to blocking and weather regime METcalcpy scripts so they point to the new mpr file write script

### Time Estimate ###
1-2 days

### Sub-Issues ###
Consider breaking the task down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [ ] Select **component(s)**
- [ ] Select **priority**
- [ ] Select **requestor(s)**

### Projects and Milestone ###
- [ ] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED CYCLE ASSIGNMENT** label
- [ ] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdataio](https://github.com/dtcenter/METdataio/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Task Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Add any new Python packages to the [METplus Components Python Requirements](https://metplus.readthedocs.io/en/develop/Users_Guide/overview.html#metplus-components-python-requirements) table.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Development** issues
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

### PR DESCRIPTION
**Pull request by CPKalb**
## Pull Request Testing ##

- [x] Describe testing already performed for these changes:</br>
Tested the use case to be sure it works

- [x] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>
Check out the following branches of METplus, METcalcpy, METplotpy, and METdataio
feature_1344_stratosphere_bias of METplus
feature_342_write_mpr_file METcalcpy
develop branch of METplotpy
develop branch of METdataio

Run 1 use cases,  s2s/UserScript_fcstGFS_obsERA_StratospherePolar.conf. Verify that the StratospherePolar use case produces output mpr files located in s2s/UserScript_fcstGFS_obsERA_StratospherePolar/mpr

The documentation is located in docs/Users_Guide/write_mpr.rst

- [x] Do these changes include sufficient documentation updates, ensuring that no errors or warnings exist in the build of the documentation? **[Yes or No]**
Yes

- [x] Do these changes include sufficient testing updates? **[Yes or No]**
Tests will be added under [issue 358](https://github.com/dtcenter/METcalcpy/issues/358)

- [x] Will this PR result in changes to the test suite? **[Yes or No]**</br>
If **yes**, describe the new output and/or changes to the existing output:</br>
No

- [x] Please complete this pull request review by **[Fill in date]**.</br>
02/13/2024

## Pull Request Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Add any new Python packages to the [METplus Components Python Requirements](https://metplus.readthedocs.io/en/develop/Users_Guide/overview.html#metplus-components-python-requirements) table.
- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [x] Complete the PR definition above.
- [ ] Ensure the PR title matches the feature or bugfix branch name.
- [ ] Define the PR metadata, as permissions allow.
Select: **Reviewer(s)**
Select: **Organization** level software support **Project** or **Repository** level development cycle **Project**
Select: **Milestone** as the version that will include these changes
- [ ] After submitting the PR, select the :gear: icon in the **Development** section of the right hand sidebar. Search for the issue that this PR will close and select it, if it is not already selected.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue and delete your feature or bugfix branch from GitHub.

### CODE REVIEW

**Comment by bikegeek** [comment]
checked out the develop version of METdataio because bugfix_247_readnc_no_lon was merged into develop and the branch no longer exists.

**Comment by CPKalb** [comment]
Ah, that's right.  I'll update the comment to reflect this

**Comment by bikegeek** [comment]
@cpkalb after finding ERRORS in my log file/unsuccessful end-to-end run, I re-ran the use case with a Process list with only one of the steps at a time.  The plotting steps are the issue:

Running wrapper: UserScript(plots_t)
02/10 17:42:44.345Z metplus.e49d1a9c (command_builder.py:563) WARNING: Could not find any INPUT files


I'm running on 'seneca'.  I used the ERA and GFS data from your scratch directory on 'derecho'

**Comment by CPKalb** [comment]
Let me take a look at this.  I did most of my testing on cheyenne, so perhaps something is not working right on a new machine.

**Review by bikegeek — APPROVED** [review]
Successfully ran the suggested use case, generated two ME plots and two RMSE plots.

**Pull request merged**
