### PR TITLE
Feature internal 46 logging

### PR DESCRIPTION
**Pull request by ishita9**
## Pull Request Testing ##

- [x] Describe testing already performed for these changes:</br>
Unit tests to ensure that nothing breaks, SonarQube scan for code reliability and duplication, physically running agg_stat.py and other modules on seneca
- [x] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>
Make sure the unit tests pass. Randomly run a few routines like agg_stat to look at the log statements. The log related entries can be made to the sample yaml files. Examples can be found under test directory. 
- [x] Do these changes include sufficient documentation updates, ensuring that no errors or warnings exist in the build of the documentation? **[Yes or No]**
Yes
- [x] Do these changes include sufficient testing updates? **[Yes or No]**
Yes
- [x] Will this PR result in changes to the test suite? **[Yes or No]**</br>
If **yes**, describe the new output and/or changes to the existing output:</br>
Yes, log output will be generated under test_dir/logs
- [x] Do these changes introduce new SonarQube findings? **[Yes or No]**</br>
If **yes**, please describe:
No.
- [ ] Please complete this pull request review by **[Fill in date]**.</br>

## Pull Request Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Add any new Python packages to the [METplus Components Python Requirements](https://metplus.readthedocs.io/en/develop/Users_Guide/appendixA.html#metplus-components-python-packages) table.
- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR definition above.
- [ ] Ensure the PR title matches the feature or bugfix branch name.
- [ ] Define the PR metadata, as permissions allow.
Select: **Reviewer(s)** and **Development** issue
Select: **Milestone** as the version that will include these changes
Select: **Coordinated METplus-X.Y Support** project for bugfix releases or **METcalcpy-X.Y.Z Development** project for official releases
- [ ] After submitting the PR, select the :gear: icon in the **Development** section of the right hand sidebar. Search for the issue that this PR will close and select it, if it is not already selected.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue and delete your feature or bugfix branch from GitHub.

### CODE REVIEW

**Comment by jprestop** [comment]
@bikegeek and @ishita9 Just wanted to ensure we were waiting for @lisagoodrich to finish up the documentation before approving this request.  There is a problem with the documentation - I know what it is I just haven't gotten to it yet (just fyi).

**Comment by ishita9** [comment]
Oh yes! Lisa needs to finish her part.

Thanks
-Ishita

**Review by bikegeek — APPROVED** [review]

**Comment by lisagoodrich** [comment]
Help!!! @bikegeek  I'm not finished yet.  I have 2 more pages of documentation to add  on feature_46_internal_46_logging branch.  Is that okay?

**Comment by bikegeek** [comment]
That is OK, I haven't closed the issue yet.  Let me know when everything is
ready to go. Thanks for working on the documentation.

**Pull request merged**
