### PR TITLE
Bugfix 329 negative bcmse

### PR DESCRIPTION
**Pull request by bikegeek**
## Pull Request Testing ##

- [x] Describe testing already performed for these changes:</br>

-    created and ran test in METcalcpy/metcalcpy/test/test_sl1l2.py using the data Molly provided that results in negative BCMSE values
-    added the test to the GitHub workflow unit_tests.yml

- [x] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

   Hank:
   verify that the METcalcpy/metcalcpy/test/test_sl1l2.py passes with the required Python Packages for METcalcpy 

   Molly:
   verify that this version is no longer responsible for erroneous plots

- [x] Do these changes include sufficient documentation updates, ensuring that no errors or warnings exist in the build of the documentation? **[NA]**

- [x] Do these changes include sufficient testing updates? **[Yes]**

- [x] Will this PR result in changes to the test suite? **[Yes]**</br>
If **yes**, describe the new output and/or changes to the existing output:</br>

- [x] Please complete this pull request review by **before beta3 release**.</br>

## Pull Request Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Add any new Python packages to the [METplus Components Python Requirements](https://metplus.readthedocs.io/en/develop/Users_Guide/overview.html#metplus-components-python-requirements) table.
- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR definition above.
- [ ] Ensure the PR title matches the feature or bugfix branch name.
- [ ] Define the PR metadata, as permissions allow.
Select: **Reviewer(s)**
Select: **Organization** level software support **Project** or **Repository** level development cycle **Project**
Select: **Milestone** as the version that will include these changes
- [ ] After submitting the PR, select the :gear: icon in the **Development** section of the right hand sidebar. Search for the issue that this PR will close and select it, if it is not already selected.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue and delete your feature or bugfix branch from GitHub.

### CODE REVIEW

**Review by mollybsmith-noaa — COMMENTED** [review]
This does remove the thrown error, but I should point out that the pre-rounding of the components before the final statistic is calculated is going to make our result values slightly off. Are we okay with this?

**Comment by bikegeek** [comment]
I believe the round-up where implemented by @Tatiana Burek
***@***.***>  to get consistency with the results produced by the
original R scripts.

---------------
Minna Win
Pronouns: she/her
National Center for Atmospheric Research
DTC/Research Applications Lab
Phone: 303-497-8423

*My work hours may not be your work hours. Please do not feel obliged to
reply to this email outside of your normal working hours.*
---------------

**Comment by bikegeek** [comment]
One more thing,  I also omitted the rounding of the me and mse and still
observed the negative bcmse values, so the rounding isn't the culprit

---------------
Minna Win
Pronouns: she/her
National Center for Atmospheric Research
DTC/Research Applications Lab
Phone: 303-497-8423

*My work hours may not be your work hours. Please do not feel obliged to
reply to this email outside of your normal working hours.*
---------------

**Comment by bikegeek** [comment]
Here is Tatiana's explanation of why there is rounding:

_Rscript performs rounding with 5 digits for all stats. This was implemented to remove the "noise" from plots and output ASCII files.
We decided to increase the number of digits to 7 in Python because of the MET output where the numbers are rounded to 7 digits._

**Comment by mollybsmith-noaa** [comment]
Okay, if we're rounding to 5 digits that should be fine. I was expecting less precision, as this was based on an older script.

**Review by mollybsmith-noaa — APPROVED** [review]

**Pull request merged**
