### PR TITLE
 reset_index is performed on the float value #322

### LINKED ISSUE #322: reset_index is performed on the float value
## Describe the Problem ##
calculate_pstd_brier , calculate_pstd_bss_smpl and calculate_pstd_resolution methods in pstd_statistics.py perform reset_index in the float value:
t_table.reset_index(inplace=True, drop=True)
This operation throws an exception and interrupts the execution.
Need to remove these statements.

### Environment ###
Describe your runtime environment:
*1. Machine: (e.g. HPC name, Linux Workstation, Mac Laptop)*
*2. OS: (e.g. RedHat Linux, MacOS)*
*3. Software version number(s)*

### To Reproduce ###
Describe the steps to reproduce the behavior:
*1. Go to '...'*
*2. Click on '....'*
*3. Scroll down to '....'*
*4. See error*
*Post relevant sample data following these instructions:*
*https://dtcenter.org/community-code/model-evaluation-tools-met/met-help-desk#ftp*

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [ ] Select **component(s)**
- [ ] Select **priority**
- [ ] Select **requestor(s)**

### Projects and Milestone ###
- [ ] Select **Organization** level **Project** for support of the current coordinated release
- [ ] Select **Repository** level **Project** for development toward the next official release or add **alert: NEED CYCLE ASSIGNMENT** label
- [ ] Select **Milestone** as the next bugfix version

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdataio](https://github.com/dtcenter/METdataio/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Bugfix Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **main_\<Version>**.
Branch name: `bugfix_<Issue Number>_main_<Version>_<Description>`
- [ ] Fix the bug and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Add any new Python packages to the [METplus Components Python Requirements](https://metplus.readthedocs.io/en/develop/Users_Guide/overview.html#metplus-components-python-requirements) table.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **main_\<Version>**.
Pull request: `bugfix <Issue Number> main_<Version> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Development** issues
Select: **Organization** level software support **Project** for the current coordinated release
Select: **Milestone** as the next bugfix version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Complete the steps above to fix the bug on the **develop** branch.
Branch name:  `bugfix_<Issue Number>_develop_<Description>`
Pull request: `bugfix <Issue Number> develop <Description>`
Select: **Reviewer(s)** and **Development** issues
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Close this issue.

### PR DESCRIPTION
**Pull request by TatianaBurek**
## Pull Request Testing ##

- [X] Describe testing already performed for these changes:
Tested on mohawk and locally using attached data
[plot_20230818_180136.agg_stat.info.txt](https://github.com/dtcenter/METcalcpy/files/12383250/plot_20230818_180136.agg_stat.info.txt)
[plot_20230818_180136.data.agg_stat.txt](https://github.com/dtcenter/METcalcpy/files/12383252/plot_20230818_180136.data.agg_stat.txt)

**REMINDER**: change values agg_stat_input and agg_stat_output based on the local configurations

- [ ] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>
     
      **Run agg_stat.py from the command line:**
      $METCALCPY_BASE/metcalcpy/agg_stat.py plot_20230818_180136.agg_stat.info

Verify that the output file you specified in the agg_stat_output setting in the plot_20230818_180136.agg_stat.info (YAML config file) produces the expected output file and the file contains tabular data that is not full of NaN's.

**REMINDER**: change values agg_stat_input and agg_stat_output based on the local configurations

- [ ] Do these changes include sufficient documentation updates, ensuring that no errors or warnings exist in the build of the documentation? **[Yes or No]**

- [ ] Do these changes include sufficient testing updates? **[Yes or No]**

- [ ] Will this PR result in changes to the test suite? **[Yes or No]**</br>
If **yes**, describe the new output and/or changes to the existing output:</br>

- [ ] Please complete this pull request review by **[Fill in date]**.</br>

## Pull Request Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Add any new Python packages to the [METplus Components Python Requirements](https://metplus.readthedocs.io/en/develop/Users_Guide/overview.html#metplus-components-python-requirements) table.
- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR definition above.
- [ ] Ensure the PR title matches the feature or bugfix branch name.
- [ ] Define the PR metadata, as permissions allow.
Select: **Reviewer(s)**
Select: **Organization** level software support **Project** or **Repository** level development cycle **Project**
Select: **Milestone** as the version that will include these changes
- [ ] After submitting the PR, select the :gear: icon in the **Development** section of the right hand sidebar. Search for the issue that this PR will close and select it, if it is not already selected.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue and delete your feature or bugfix branch from GitHub.

### CODE REVIEW

**Comment by bikegeek** [comment]
@TatianaBurek , do you have a screenshot of what the plot is supposed to look like?  I'm trying to generate this from the command line with the provided yaml file and I can't seem to get the correct number of plotting settings.

**Comment by TatianaBurek** [comment]
Attached are the plot and XML files
plot_20230821_174714
[plot_20230821_174714.xml.txt](https://github.com/dtcenter/METcalcpy/files/12399383/plot_20230821_174714.xml.txt)

**Comment by bikegeek** [comment]
When generating from the command line, an empty plot is generated and the log file does not indicate any errors.  The 
plot_20230818_180136.points1 contains all NaN's but the dump points generated by METviewer contains valid numerical values (except for first row).  

This is the configuration file used:
[plot.yaml.txt](https://github.com/dtcenter/METcalcpy/files/12402680/plot.yaml.txt)

also tried using the originally supplied config file from the Pull Request Testing section (modified to include the plot_ci, plot_disp, series_order, user_legend, series_symbols, and colors):
[plot_20230818_180136.agg_stat.yaml.txt](https://github.com/dtcenter/METcalcpy/files/12402692/plot_20230818_180136.agg_stat.yaml.txt)


Using this data as input:
[plot_20230818_180136.data.agg_stat.txt](https://github.com/dtcenter/METcalcpy/files/12402695/plot_20230818_180136.data.agg_stat.txt)

With both develop and main_v2.1 versions of METplotpy and the issue_322_reset_index branch of METcalcpy.

Can you take a look and verify if this is also creating an empty line plot?

**Comment by TatianaBurek** [comment]
The attached files are provided to be used to test pstg_statistics.py using agg_stats.py
Only 2 location parameters in [plot_20230818_180136.agg_stat.info.txt](https://github.com/dtcenter/METcalcpy/files/12383250/plot_20230818_180136.agg_stat.info.txt) should be modified:
agg_stat_input and agg_stat_output
to run :
/METcalcpy/metcalcpy/agg_stat.py  plot_20230818_180136.agg_stat.info
The result of the run is the data file. This file should have values different then NA in the stat_value column.
This test doesn't require running METplotpy  and creating plots

**Comment by bikegeek** [comment]
I updated the Pull Request Testing section with these instructions.  I wanted to make sure that generating a plot from the command line was unaffected, as the UFS team might be interested in doing this from the command line.

**Review by bikegeek — APPROVED** [review]
ran agg_stat.py from the command line and created a valid output file.

**Pull request merged**
