### PR TITLE
Feature 152 nco packages

### PR DESCRIPTION
**Pull request by bikegeek**
## Pull Request Testing ##

- [x] Describe testing already performed for these changes:</br>
   created the conda environment on 'seneca', metcalcpy_py38 and ran all tests in the METcalcpy/test
   directory

- [x] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

    on 'seneca', use the metcalcpy_py38 conda environment (conda activate /home/met_test/.conda/envs/metcalcpy_py38)

   run pytest on all the tests in the METcalcpy/test directory:

-     cd to METcalcpy/test
-     pytest <----this will run all the pytest tests

- [x] Do these changes include sufficient documentation updates, ensuring that no errors or warnings exist in the build of the documentation? **[No]**

- [x] Do these changes include sufficient testing updates? **[NA]**

- [X] Will this PR result in changes to the test suite? **[No]**</br>
If **yes**, describe the new output and/or changes to the existing output:</br>

- [x] Please complete this pull request review by  At your earliest convenience.  I am using these packages to build upon to create the METplotpy packages.</br>

## Pull Request Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [x] Review the source issue metadata (required labels, projects, and milestone).
- [x] Complete the PR definition above.
- [x] Ensure the PR title matches the feature or bugfix branch name.
- [x] Define the PR metadata, as permissions allow.
Select: **Reviewer(s)**
Select: **Organization** level software support **Project** or **Repository** level development cycle **Project**
Select: **Milestone** as the version that will include these changes
- [x] After submitting the PR, select **Linked issues** with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue and delete your feature or bugfix branch from GitHub.

### CODE REVIEW

**Comment by hankenstein2** [comment]
So strangely when I conda activate the metcalcpy_py38 as fisherh I am missing the pyyaml package.
When I activate it as met_test I am missing the matplotlib package.

I am guessing that pyyaml was installed via pip and has permission issues when fisherh uses the environment.

**Comment by bikegeek** [comment]
I managed to create the conda environment for METcalcpy to omit the
matplotlib package (by starting "fresh"), so I wouldn't worry about
matplotlib not being present in the metcalcpy_py38 environment.  I did not
install the pyyaml or yaml packages- they aren't needed for the "core"
METcalcpy.   They should be present for the metplotpy_py38 environment.
---------------
Minna Win
Pronouns: she/her
National Center for Atmospheric Research
Developmental Testbed Center
Phone: 303-497-8423
Fax:   303-497-8401
---------------

**Comment by bikegeek** [comment]
I stand corrected, I looked at my notes and I did indeed explicitly install
pyyaml (5.4.1, yaml 0.2.5).  I didn't use pip for any installation to avoid
these issues.  I wonder if I should try mamba.

-M
---------------
Minna Win
Pronouns: she/her
National Center for Atmospheric Research
Developmental Testbed Center
Phone: 303-497-8423
Fax:   303-497-8401
---------------

**Comment by hankenstein2** [comment]
Just to not complicate things. I ran this as user met_test and everything ran perfectly so I am approving this pull request and we will deal with transferring conda environments later.

**Review by hankenstein2 — APPROVED** [review]

**Pull request merged**
