### PR TITLE
Bugfix 251 test scorecard

### PR DESCRIPTION
**Pull request by bikegeek**
## Pull Request Testing ##

- [x] Describe testing already performed for these changes:</br>

Create a python 3.8 conda environment with these NCO metcalcpy minimal requirements:

    MetPy==1.3.1
    netcdf4==1.6.2 <- NOTE: this wasn't installed on 'acorn', this needs to be included
    numpy==1.22.0
    pandas==1.5.1
    pip==22.2.2
    pytest==6.2.2
    python-dateutil==2.8.2
    PyYAML==5.4.1
    scipy==1.8.1
    xarray==2022.3.0

Run tests using this script (to run only the 'basic' tests that don't use image comparison 3rd party packages):

[run_basics.sh.txt](https://github.com/dtcenter/METcalcpy/files/10273378/run_basics.sh.txt)

    Copy the script to the METcalcpy/test/ directory
    Remove the .txt extension
    chmod 777 run_basics.sh
    from the METcalcpy/test directory, run sh ./run_basics.sh

Verified that the specified tests passed (some tests are skipped in test_agg_stats_and_boots.py because they take a very long time to run) .

NOTE test_event_equalize.py tests is not included in the run_basics.sh script because there is another Github issue https://github.com/dtcenter/METcalcpy/issues/250 for addressing the failing test in test_event_equalization.py

- [x] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

Perform the same testing as above

- [x] Do these changes include sufficient documentation updates, ensuring that no errors or warnings exist in the build of the documentation? **[NA]**

- [x] Do these changes include sufficient testing updates? **[NA]**

- [x] Will this PR result in changes to the test suite? **[ No]**</br>
If **yes**, describe the new output and/or changes to the existing output:</br>

- [x] Please complete this pull request review by **Bugfix release**.</br>

## Pull Request Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR definition above.
- [ ] Ensure the PR title matches the feature or bugfix branch name.
- [ ] Define the PR metadata, as permissions allow.
Select: **Reviewer(s)**
Select: **Organization** level software support **Project** or **Repository** level development cycle **Project**
Select: **Milestone** as the version that will include these changes
- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue and delete your feature or bugfix branch from GitHub.

### CODE REVIEW

**Review by jprestop — CHANGES_REQUESTED** [review]
Hi @bikegeek.  The [same problem](https://github.com/dtcenter/METcalcpy/pull/255#pullrequestreview-1244506920) I mentioned in PR #255 exists here.

**Review by jprestop — COMMENTED** [review]
@bikegeek Also, it appears that this PR and [Feature 251 test scorecard #253](https://github.com/dtcenter/METcalcpy/pull/253) are both requesting to be merged into main_v2.0:
```
[Feature 251 test scorecard #253](https://github.com/dtcenter/METcalcpy/pull/253)
"bikegeek wants to merge 3 commits into main_v2.0 from feature_251_test_scorecard"
 
[Bugfix 251 test scorecard #256](https://github.com/dtcenter/METcalcpy/pull/256)
“bikegeek wants to merge 3 commits into main_v2.0 from bugfix_251_test_scorecard”
```
But I think PR #253 should be going into develop.  However, I'm not sure what branch it was created off of or how to tell.

**Comment by bikegeek** [comment]
Base changed to 'develop' branch.
---------------
Minna Win
Pronouns: she/her
National Center for Atmospheric Research
Developmental Testbed Center
Phone: 303-497-8423
Fax:   303-497-8401
---------------

**Comment by jprestop** [comment]
I thought the base for this bugfix branch should be main_v2.0 and the base for the feature branch should be main_v2.0?

**Comment by bikegeek** [comment]
I just verified that the bugfix_251 base is main_v2.0 and the feature_251
base is develop.  The previous comment was incorrect.  I was looking at the PR for the feature_251 

---------------
Minna Win
Pronouns: she/her
National Center for Atmospheric Research
Developmental Testbed Center
Phone: 303-497-8423
Fax:   303-497-8401
---------------

**Comment by jprestop** [comment]
> I just verified that the bugfix_251 base is main_v2.0 and the feature_251
base is develop.  The previous comment was incorrect.  I was looking at the PR for the feature_251

Awesome.  Thank you so much!

**Comment by jprestop** [comment]
Hi @bikegeek.  I just did a git pull and didn't see any changes here.  I was wondering if maybe my previous comment was missed or misinterpreted due to the conversation about the branches:

> Hi @bikegeek. The https://github.com/dtcenter/METcalcpy/pull/255#pullrequestreview-1244506920 I mentioned in PR https://github.com/dtcenter/METcalcpy/pull/255 exists here.

This branch has the same issue as PR #255 with regard to "FAILED test_lon_360_to_180.py::test_lon_from_360_to_180 - AttributeError: module 'numpy' has no attribute 'float'", unfortunately.

**Review by jprestop — APPROVED** [review]
Hi @bikegeek.  I checked out the updates and ran the tests on Acorn.  I'm happy to report that test_lon_360_to_180.py along with the others all passed.  I approve this request.  Sorry for the delay in approval.

**Pull request merged**
