### PR TITLE
Feature 251 test scorecard

### LINKED ISSUE #251: Fix test_scorecard.py with pandas-1.5.1
## Describe the Problem ##
Running the pytests on WCOSS2 Acorn produced this error:
```
================================================================================= ERRORS =================================================================================
___________________________________________________________________ ERROR collecting test_scorecard.py ___________________________________________________________________
ImportError while importing test module '/apps/sw_review/emc/METcalcpy/METcalcpy-2.0.0/test/test_scorecard.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/apps/spack/python/3.8.6/intel/19.1.3.304/pjn2nzkjvqgmjw4hmyz43v5x4jbxjzpk/lib/python3.8/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
test_scorecard.py:4: in <module>
    from metcalcpy.scorecard import Scorecard, pd
../metcalcpy/scorecard.py:47: in <module>
    from pandas.core.common import SettingWithCopyWarning
E   ImportError: cannot import name 'SettingWithCopyWarning' from 'pandas.core.common' (/u/julie.prestopnik/.local/lib/python3.8/site-packages/pandas/core/common.py)
======================================================================== short test summary info =========================================================================
ERROR test_scorecard.py
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
============================================================================ 1 error in 2.23s ============================================================================
```

### Expected Behavior ###
This pytest should pass.

### Environment ###
Describe your runtime environment:
1. Machine: WCOSS2 Acorn
2. OS: SUSE Linux Enterprise Server 15 SP3, Linux alogin01 5.3.18-150300.59.90-default
3. Software version number(s): METcalcpy-2.0.0

### To Reproduce ###
Describe the steps to reproduce the behavior:
*1. Go to '...'*
*2. Click on '....'*
*3. Scroll down to '....'*
*4. See error*
*Post relevant sample data following these instructions:*
*https://dtcenter.org/community-code/model-evaluation-tools-met/met-help-desk#ftp*
Ran _python3 -m pytest_  in /apps/sw_review/emc/METcalcpy/METcalcpy-2.0.0/test

### Relevant Deadlines ###
ASAP

### Funding Source ###
2792542, 2773542

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Select **Organization** level **Project** for support of the current coordinated release
- [x] Select **Repository** level **Project** for development toward the next official release or add **alert: NEED PROJECT ASSIGNMENT** label
- [x] Select **Milestone** as the next bugfix version

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdataio](https://github.com/dtcenter/METdataio/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Bugfix Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **main_\<Version>**.
Branch name: `bugfix_<Issue Number>_main_<Version>_<Description>`
- [ ] Fix the bug and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **main_\<Version>**.
Pull request: `bugfix <Issue Number> main_<Version> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Development** issues
Select: **Organization** level software support **Project** for the current coordinated release
Select: **Milestone** as the next bugfix version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Complete the steps above to fix the bug on the **develop** branch.
Branch name:  `bugfix_<Issue Number>_develop_<Description>`
Pull request: `bugfix <Issue Number> develop <Description>`
Select: **Reviewer(s)** and **Development** issues
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Close this issue.

### PR DESCRIPTION
**Pull request by bikegeek**
## Pull Request Testing ##

- [x] Describe testing already performed for these changes:</br>
Create a python 3.8 conda environment with these NCO metcalcpy minimal requirements:

> MetPy==1.3.1
> netcdf4==1.6.2 <- **NOTE**: this wasn't installed on 'acorn', this needs to be included
> numpy==1.22.0
> pandas==1.5.1
> pip==22.2.2
> pytest==6.2.2
> python-dateutil==2.8.2
> PyYAML==5.4.1
> scipy==1.8.1
> xarray==2022.3.0

Run tests using this script (to run only the 'basic' tests that don't use image comparison 3rd party packages):
----------
[run_basics.sh.txt](https://github.com/dtcenter/METcalcpy/files/10273378/run_basics.sh.txt)

1. Copy the script to the METcalcpy/test/ directory
2. Remove the .txt extension
3. chmod 777 run_basics.sh
4. from the METcalcpy/test directory, run sh ./run_basics.sh

Verified that the **specified tests passed** (some tests are skipped in test_agg_stats_and_boots.py because they take a very long time to run) .

 **NOTE**  **_test_event_equalize.py tests is not included in the run_basics.sh script_** because there is another Github issue #250 for addressing the failing test in test_event_equalization.py

- [x] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>
 
   Perform the same testing as above

- [x] Do these changes include sufficient documentation updates, ensuring that no errors or warnings exist in the build of the documentation? **[NA]**

- [x] Do these changes include sufficient testing updates? **[Yes]**

- [x] Will this PR result in changes to the test suite? **[No]**</br>
If **yes**, describe the new output and/or changes to the existing output:</br>

- [x] Please complete this pull request review by **[by NCO deadline]**.</br>

## Pull Request Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [x] Review the source issue metadata (required labels, projects, and milestone).
- [x] Complete the PR definition above.
- [x] Ensure the PR title matches the feature or bugfix branch name.
- [x] Define the PR metadata, as permissions allow.
Select: **Reviewer(s)**
Select: **Organization** level software support **Project** or **Repository** level development cycle **Project**
Select: **Milestone** as the version that will include these changes
- [x] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue and delete your feature or bugfix branch from GitHub.

### CODE REVIEW

**Review by jprestop — APPROVED** [review]
I added the "==1.6.2" to "netcdf" in the nco_metcalcpy_requirements.txt file, and I am happy to report that the scorecard test now passes on WCOSS2 Acorn!  

The documentation test was not passing due to this warning for release-notes.rst:
```
WARNING: Inline strong start-string without end-string.
```
Once I added a fix for that, all of the documentation tests now pass.  I approve this request.  Thanks for your work on this!  I see this is in a feature branch going into main_v2.0.  @bikegeek, will there also be a fix for the develop branch?

**Comment by jprestop** [comment]
Also, @bikegeek, please tell me is netcdf4 1.6.2  required?  We previously told NCO 1.6.0.  I'll assume we actually need 1.6.2 or higher unless I hear differently from you.

(Note that I corrected the above - it used to say numpy instead of netcdf)

**Comment by bikegeek** [comment]
@Julie Prestopnik ***@***.***>
, we need numpy 1.22 or above, or are you referring to pandas?  I believe
we agreed upon pandas 1.5.1.

---------------
Minna Win
Pronouns: she/her
National Center for Atmospheric Research
Developmental Testbed Center
Phone: 303-497-8423
Fax:   303-497-8401
---------------

**Comment by jprestop** [comment]
My apologies, @bikegeek, I meant to ask about netcdf4:

> netcdf4==1.6.2 <- NOTE: this wasn't installed on 'acorn', this needs to be included

**Comment by bikegeek** [comment]
@Julie Prestopnik ***@***.***> , netcdf 1.6.2 works on 'seneca' in my
testing environment.  I have also been successfully using 1.5.8, but to
future-proof, we should use the 1.6.2 version.
---------------
Minna Win
Pronouns: she/her
National Center for Atmospheric Research
Developmental Testbed Center
Phone: 303-497-8423
Fax:   303-497-8401
---------------

**Comment by jprestop** [comment]
See [this comment](https://github.com/dtcenter/METcalcpy/pull/256#pullrequestreview-1244537249) from PR #256.

**Comment by bikegeek** [comment]
This is correctly merging into the 'develop' branch.  The feature_251 branch was branched from 'develop' and verified as such.

**Comment by jprestop** [comment]
> This is correctly merging into the 'develop' branch. The feature_251 branch was branched from 'develop' and verified as such.

Awesome. Thank you!

**Pull request merged**
